import { Content } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div class="content">
        <header class="header">
        <h1>Varshith konda</h1> 
        <nav> 
          <Link href='/'>Home</Link>
          <Link href='/blog'>Blog</Link>
        
        
        </nav>
        </header>
        {children}
        </div>
        <div class = "socialdiv">
         <div class="social" ><a href = "https://github.com/darthvader2">Github</a></div>
         <div class="social"><a href = "https://www.linkedin.com/in/konda-varshith/">LinkedIn</a></div>
        </div>
        </body>
    
    </html>
  )
}
