import { Content } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div class="content">
        <header class="header">
        <h1>Hello</h1> 
        <nav> 
          <Link href='/'>Home</Link>
          <Link href='/about'>About</Link>
        
        
        </nav>
        </header>
        {children}
        </div>
        </body>
    
    </html>
  )
}
