import { NextResponse } from "next/server";
import http from "node:http";
import https from "node:https";

export const runtime = "nodejs";

function extractAnswerText(responseJson) {
  const chatContent = responseJson?.choices?.[0]?.message?.content;
  if (typeof chatContent === "string" && chatContent.trim()) {
    return chatContent.trim();
  }

  if (Array.isArray(chatContent)) {
    const textChunks = chatContent
      .map((part) => {
        if (typeof part?.text === "string") {
          return part.text;
        }

        if (typeof part?.text?.value === "string") {
          return part.text.value;
        }

        return "";
      })
      .filter(Boolean);

    if (textChunks.length > 0) {
      return textChunks.join("\n").trim();
    }
  }

  if (typeof responseJson?.output_text === "string" && responseJson.output_text.trim()) {
    return responseJson.output_text.trim();
  }

  const output = responseJson?.output;
  if (!Array.isArray(output)) {
    return "";
  }

  const textParts = [];

  for (const item of output) {
    const content = item?.content;
    if (!Array.isArray(content)) {
      continue;
    }

    for (const block of content) {
      if (block?.type === "output_text" && typeof block?.text === "string") {
        textParts.push(block.text);
      }
    }
  }

  return textParts.join("\n").trim();
}

function extractDeltaText(deltaContent) {
  if (typeof deltaContent === "string") {
    return deltaContent;
  }

  if (Array.isArray(deltaContent)) {
    return deltaContent
      .map((part) => {
        if (typeof part?.text === "string") {
          return part.text;
        }

        if (typeof part?.text?.value === "string") {
          return part.text.value;
        }

        return "";
      })
      .join("");
  }

  return "";
}

function buildTextStreamResponse(stream) {
  return new Response(stream, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "no-cache, no-transform",
      "X-Accel-Buffering": "no"
    }
  });
}

function streamTextFromPlainText(text) {
  const encoder = new TextEncoder();
  return new ReadableStream({
    start(controller) {
      controller.enqueue(encoder.encode(text));
      controller.close();
    }
  });
}

function streamTextFromNodeResponse(nodeResponse) {
  const contentType = String(nodeResponse.headers["content-type"] || "");
  const encoder = new TextEncoder();

  return new ReadableStream({
    async start(controller) {
      try {
        if (contentType.includes("text/event-stream")) {
          let buffer = "";

          for await (const chunk of nodeResponse) {
            buffer += chunk.toString("utf8");
            const lines = buffer.split("\n");
            buffer = lines.pop() || "";

            for (const rawLine of lines) {
              const line = rawLine.trim();
              if (!line || !line.startsWith("data:")) {
                continue;
              }

              const payload = line.slice(5).trim();
              if (!payload || payload === "[DONE]") {
                continue;
              }

              try {
                const chunkJson = JSON.parse(payload);
                const delta = chunkJson?.choices?.[0]?.delta?.content;
                const deltaText = extractDeltaText(delta);
                if (deltaText) {
                  controller.enqueue(encoder.encode(deltaText));
                  continue;
                }

                const fullText = extractAnswerText(chunkJson);
                if (fullText) {
                  controller.enqueue(encoder.encode(fullText));
                }
              } catch {
                // Ignore malformed SSE payloads.
              }
            }
          }

          controller.close();
          return;
        }

        let rawText = "";
        for await (const chunk of nodeResponse) {
          rawText += chunk.toString("utf8");
        }

        let text = rawText.trim();
        if (text) {
          try {
            const json = JSON.parse(text);
            text = extractAnswerText(json) || text;
          } catch {
            // Keep raw text if it is not JSON.
          }
        }

        controller.enqueue(encoder.encode(text || "No answer generated by the model."));
        controller.close();
      } catch (error) {
        controller.error(error);
      }
    }
  });
}

function readNodeResponseText(nodeResponse) {
  return new Promise((resolve, reject) => {
    let text = "";

    nodeResponse.setEncoding("utf8");
    nodeResponse.on("data", (chunk) => {
      text += chunk;
    });
    nodeResponse.on("end", () => resolve(text));
    nodeResponse.on("error", reject);
  });
}

function postJson(openAiApiUrl, apiKey, payload) {
  return new Promise((resolve, reject) => {
    const url = new URL(openAiApiUrl);
    const transport = url.protocol === "https:" ? https : http;
    const requestBody = JSON.stringify(payload);

    const request = transport.request(
      {
        protocol: url.protocol,
        hostname: url.hostname,
        port: url.port || undefined,
        path: `${url.pathname}${url.search}`,
        method: "POST",
        headers: {
          Authorization: `Bearer ${apiKey}`,
          "Content-Type": "application/json",
          Accept: "text/event-stream, application/json, text/plain",
          "Accept-Encoding": "identity",
          "Content-Length": Buffer.byteLength(requestBody)
        }
      },
      (response) => {
        resolve(response);
      }
    );

    request.on("error", reject);
    request.setTimeout(0);
    request.write(requestBody);
    request.end();
  });
}

export async function POST(request) {
  try {
    const body = await request.json();
    const prompt = body?.prompt?.trim();

    if (!prompt) {
      return NextResponse.json({ error: "Prompt is required." }, { status: 400 });
    }

    const apiKey = process.env.OPENAI_API_KEY || process.env.OPENAI_KEY;
    const openAiApiUrl = process.env.OPENAI_API_URL || process.env.OPENAI_URL;
    const model = process.env.OPENAI_MODEL || "gpt-4.1-mini";

    if (!apiKey) {
      return buildTextStreamResponse(
        streamTextFromPlainText(
          `Demo mode: received your question "${prompt}". Add OPENAI_API_KEY (or OPENAI_KEY) in your environment to enable live LLM answers.`
        )
      );
    }

    if (!openAiApiUrl) {
      return NextResponse.json(
        { error: "Missing OPENAI_API_URL (or OPENAI_URL) in environment." },
        { status: 500 }
      );
    }

    const buildRequestBody = (useChatCompletions) => {
      if (useChatCompletions) {
        return {
          model,
          messages: [{ role: "user", content: prompt }],
          stream: true,
          temperature: 0.7,
          max_tokens: 300
        };
      }

      return {
        model,
        input: prompt,
        stream: true,
        temperature: 0.7,
        max_output_tokens: 300
      };
    };

    const useChatCompletionsFromUrl = /chat\/completions/i.test(openAiApiUrl);
    let nodeResponse = await postJson(openAiApiUrl, apiKey, buildRequestBody(useChatCompletionsFromUrl));
    let errorText = "";

    if (nodeResponse.statusCode < 200 || nodeResponse.statusCode >= 300) {
      errorText = await readNodeResponseText(nodeResponse);

      if (!useChatCompletionsFromUrl && /messages.*must be a list/i.test(errorText)) {
        nodeResponse = await postJson(openAiApiUrl, apiKey, buildRequestBody(true));
        errorText = "";
      }
    }

    if (nodeResponse.statusCode < 200 || nodeResponse.statusCode >= 300) {
      if (!errorText) {
        errorText = await readNodeResponseText(nodeResponse);
      }

      return NextResponse.json(
        { error: "LLM backend request failed.", details: errorText },
        { status: 502 }
      );
    }

    return buildTextStreamResponse(streamTextFromNodeResponse(nodeResponse));
  } catch {
    return NextResponse.json(
      { error: "Unexpected server error while generating the AI response." },
      { status: 500 }
    );
  }
}
